### ISSUE TITLE
Initial App

### ISSUE THREAD

**Issue by mwarman** [leanstacks/react-starter-kit#1]
## Description

Initialize the repository using the leanstacks/skeleton-ui-react repo as a base. Include the components from the leanstacks/react-common repo as common components in the starter kit.

#### Tasks
- [x] Copy source from `skeleton-ui-react`
- [x] Update README
- [x] Update package.json
- [x] Remove any references to `skeleton-ui-react`
- [x] Relax the login password requirements to accept any password
- [ ] Add the components from `react-common` into the `src/common` directory and remove `react-common` dependency
